# Site settings
title: Tech Ox
email: oscar.delgadillo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bringing beginner tech topics to the masses.
baseurl: "patchwork-gh-pages-24"
url: "http://countaight.github.io"
twitter_username: countaightblah
github_username:  countaight
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index